# Generated by Django 2.0.6 on 2018-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=300)),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('link', models.TextField(default='0')),
                ('type', models.CharField(default='default name', max_length=300)),
                ('category', models.CharField(default='default name', max_length=300)),
                ('keyword', models.CharField(default='default name', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=300)),
                ('level', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('keyword', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('requirement', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StandardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StandardRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=300)),
                ('requirementList', models.TextField(default='name')),
            ],
        ),
    ]
