# Generated by Django 2.0.6 on 2018-12-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181215_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='keyword',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
