# Generated by Django 2.0.6 on 2018-12-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181215_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='category',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standard',
            name='requirement',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
