# Generated by Django 2.0.6 on 2018-12-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181215_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
