# Generated by Django 2.1.4 on 2018-12-15 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181215_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keyword',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prkeyword', to='app.KeyWords'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prcategory', to='app.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prtype', to='app.ProductType'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stcategory', to='app.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stkeyword', to='app.KeyWords'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sttype', to='app.StandardRequirement'),
        ),
    ]
